[package]
name = "slippybot"
version = "0.1.0"
authors = ["Kevin Rauwolf <kevin@fgsake.org>"]

[dependencies]
slack = "*"
regex = "*"
log = "*"
env_logger = "*"
cron = "*"
chrono = "*"
rustc-serialize = "*"
rand = "*"
